// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixProjectWithToolWindowCommunity
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixProjectWithToolWindowCommunity.1c7763c7-3689-46d9-98d1-0b35c098bbb1";
        public const string Name = "VsixProjectWithToolWindowCommunity";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alexander Gayko";
        public const string Tags = "";
    }
}
