// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VsixProjectWithToolWindowCommunity
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsixProjectWithToolWindowCommunityString = "fdb76c82-3883-442f-b045-b18d3e3708ca";
        public static Guid VsixProjectWithToolWindowCommunity = new Guid(VsixProjectWithToolWindowCommunityString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}